### ISSUE TITLE
Packr is not creating app

### ISSUE THREAD

**Issue by f-lima** [libgdx/packr#105]
This is the error:

Removing foreign platform libs ...
Exception in thread "main" org.zeroturnaround.zip.ZipException: java.util.zip.ZipException: error in opening zip file
	at org.zeroturnaround.zip.ZipUtil.rethrow(ZipUtil.java:2556)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:379)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:704)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:689)
	at com.badlogicgames.packr.PackrReduce.removePlatformLibs(PackrReduce.java:204)
	at com.badlogicgames.packr.Packr.pack(Packr.java:65)
	at com.badlogicgames.packr.Packr.main(Packr.java:308)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:360)
	... 5 more

Could you put an option to don't remove platform libs?
I am trying to pack an app to Mac.

**Comment by karlsabo** [comment]
zeroturnaround is no longer used in Packr, please try the latest version.
