### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by jordiperendreu** [libgdx/packr#109]
Hi!

I was trying to use Packr for my project and I'm having problems with the execution of the build

The configuration is:
`{
    "platform": "linux64",
    "jdk": "/opt/java/jdk1.8.0_131/jre/",
    "executable": "core",
    "classpath": [
        "target/core-0.0.1-SNAPSHOT.jar"
    ],
    "mainclass": "com.testapp.core.GameApplication",
    "vmargs": [
       "Xmx1G"
    ],
    "resources": [
    ],
    "minimizejre": "soft",
    "output": "out-linux64"
}`

The build works perfectly but the execution of the binary is failing:
`Exception in thread "main" java.lang.ClassNotFoundException: com.testapp.core.GameApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Error: failed to load/find main class com.testapp.core.GameApplication`

But the class is on the jar file:
`BOOT-INF/classes/com/testapp/core/GameApplication.class`

Can you help me? 

Thanks in advance!

**Comment by code-disaster** [comment]
The `BOOT-INF/classes/com/...` path looks suspicious. I would expect it to be just `com/...` in the root folder of the JAR file.

**Comment by karlsabo** [comment]
Closing due to lack of activity.

**Comment by humble92** [comment]
I have the same error at linux side. And the path of `BOOT-INF/classes/com/` is correct when we build that using mvn.
