### ISSUE TITLE
Can't get multiple arguments to work

### ISSUE THREAD

**Issue by Tharkius** [libgdx/packr#118]
I've been hitting my head trying to understand how exactly do I specify multiple arguments for a parameter. This is the code I'm using:

` java -jar packr.jar --platform windows64 --output out/windows64 --classpath C:/Users/Me/IdeaProjects/Foobar/out/Foobar.jar C:/Users/Me/.m2/repository/foo/bar/foo.jar -- build.config.json`

I've tried doing it in many other possible ways but still can't get it to work. I'm following the example presented on the readme, but this statement doesn't seem to hold true:

> the config file name is delimited by -- because the option prior to it, --vmargs, allows multiple arguments

I always get an error simillar to this:

```
Exception in thread "main" com.eclipsesource.json.ParseException: Expected name at 14:0
        at com.eclipsesource.json.JsonParser.error(JsonParser.java:371)
        at com.eclipsesource.json.JsonParser.expected(JsonParser.java:364)
        at com.eclipsesource.json.JsonParser.readName(JsonParser.java:145)
        at com.eclipsesource.json.JsonParser.readObject(JsonParser.java:128)
        at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:83)
        at com.eclipsesource.json.JsonParser.parse(JsonParser.java:62)
        at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105)
        at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138)
        at com.badlogicgames.packr.PackrConfig.readConfigJson(PackrConfig.java:144)
        at com.badlogicgames.packr.PackrConfig.<init>(PackrConfig.java:97)
        at com.badlogicgames.packr.Packr.main(Packr.java:308)
```

**Comment by code-disaster** [comment]
The exception says there's an error in your build.config.json, not the command line.

**Comment by Tharkius** [comment]
Yap, that's correct. I was missing some properties in the json file, I thought it was enough to pass them as command-line arguments. You can close the issue :)
