### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/media/sound/JDK13Services

### ISSUE THREAD

**Issue by cogmeta** [libgdx/packr#140]
I am getting following error on mac os after running application. It looks like com/sun/media/sound lib is stripped off. Anyway to avoid that?

Exception in thread "Thread-2" java.lang.NoClassDefFoundError: com/sun/media/sound/JDK13Services
	at javax.sound.sampled.AudioSystem.getProviders(AudioSystem.java:1631)
	at javax.sound.sampled.AudioSystem.getMixerProviders(AudioSystem.java:1378)
	at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:411)

**Comment by cogmeta** [comment]
Remove--minimizejre soft \
