### ISSUE TITLE
With exe generated by Packr, app closes when HTTP request code is run

### ISSUE THREAD

**Issue by SageBinder** [libgdx/packr#149]
Related StackOverFlow question: https://stackoverflow.com/questions/57507676/packaging-libgdx-program-to-exe-with-packr-breaks-code-which-opens-url-stream

In my program LibGDX program, I obtain the user's IP by contacting https://api.ipify.org. I tried using both LibGDX HTTP methods and standard Java URL methods. The code works when I run the jarfile directly, but causes the app to exit when I run the exe

I compiled and packaged my app with JDK 11.0.1. I manually created the jre folder which Packr looks for and copied bin and lib into it. Here's the Packr config I used:
```json
{
    "platform": "windows64",
    "jdk": "C:\\Program Files\\Java\\jdk-11.0.1",
    "executable": "ShengJi-win64",
    "classpath": [
        "desktop-1.0.jar"
    ],
    "removelibs": [
        "desktop-1.0.jar"
    ],
    "mainclass": "com.sage.shengji.desktop.DesktopLauncher",
    "minimizejre": "soft",
    "output": "out-windows64"
}
```
This code, in the show() method for one of my Screens, doesn't work when I run the exe:
```java
            Net.HttpRequest httpGet = new Net.HttpRequest(Net.HttpMethods.GET);
            System.out.println("After httpGet object creation");
            httpGet.setUrl("https://api.ipify.org");
            System.out.println("After set httpGet url");

            Gdx.net.sendHttpRequest(httpGet, new Net.HttpResponseListener() {
                @Override
                public void handleHttpResponse(Net.HttpResponse httpResponse) {
                    System.out.println("in handleHttpResponse()");
                }

                @Override
                public void failed(Throwable t) {
                    System.out.println("in failed()");
                }

                @Override
                public void cancelled() {
                    System.out.println("in cancelled()");
                }
            });
            System.out.println("After Gdx.net.sendHttpRequest()");
```
It works as intended when I run the jarfile directly. However, when I run the exe and print to a log file, "After Gdx.net.sendHttpRequest()" is never printed, and neither are any of the print statements in the HttpRequestListener's methods. As far as I can tell, the rest of the app works fine with the exe. When I put the faulty code in a separate thread, the app does not close and all other parts seem to work correctly.

**Comment by code-disaster** [comment]
some random ideas:

- Try packing without minimizejre. It might remove things you need, and may do bad things on Java 9+ especially.
- Run the executable with `--cli --console --verbose`, and see if it shows you a stack trace.

**Comment by SageBinder** [comment]
Removing minimizejre didn't seem to work. I also tried removing removelibs, but that didn't work either. I did get a stacktrace:
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.base/java.security.Provider$Service.getImplClass(Provider.java:1848)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1824)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
        at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
        at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
        at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:335)
        at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:95)
        at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
        at java.base/java.net.URL.openConnection(URL.java:1051)
        at com.badlogic.gdx.net.NetJavaImpl.sendHttpRequest(NetJavaImpl.java:151)
        at com.badlogic.gdx.backends.lwjgl.LwjglNet.sendHttpRequest(LwjglNet.java:41)
        at com.sage.shengji.client.screens.LobbyScreen.show(LobbyScreen.java:178)
        at com.badlogic.gdx.Game.setScreen(Game.java:61)
        at com.sage.shengji.client.ShengJiGame.showLobbyScreen(ShengJiGame.java:77)
        at com.sage.shengji.client.screens.CreateGameScreen$2.changed(CreateGameScreen.java:168)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:183)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:148)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:131)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:94)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:350)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:342)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

When I use the standard Java classes by opening stream to a `new URL(...)` instead of LibGDX's, I get this stack trace:
```
Exception in thread "Thread-1" java.lang.ExceptionInInitializerError
        at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
        at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2630)
        at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2652)
        at java.base/sun.security.ssl.SSLCipher.isUnlimited(SSLCipher.java:566)
        at java.base/sun.security.ssl.SSLCipher.<init>(SSLCipher.java:498)
        at java.base/sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:174)
        at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:67)
        at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:356)
        at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:587)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:332)
        at java.base/java.security.Provider$Service.getImplClass(Provider.java:1842)
        at java.base/java.security.Provider$Service.newInstance(Provider.java:1818)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:166)
        at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:97)
        at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
        at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:334)
        at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:96)
        at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
        at java.base/java.net.URL.openConnection(URL.java:1074)
        at java.base/java.net.URL.openStream(URL.java:1140)
        at com.sage.shengji.client.screens.CreateGameScreen.lambda$uiSetup$0(CreateGameScreen.java:102)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:120)
        ... 27 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
        at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:326)
        at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:111)
        at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:108)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:551)
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:107)
        ... 27 more```

It does seem like Packr is removing some necessary classes, but this happens even when I don't minimizejre.

**Comment by code-disaster** [comment]
Packr doesn't remove anything without minimizejre. And when it does, it only removes full packages, but your stack trace shows other sun.security references.

My suspicion is that java.exe does something - either security or ClassLoader related - what's missing if the VM is created via JNI. But I have no idea what that would be.

**Comment by karlsabo** [comment]
Packr minimizejre was created for Java 8 JREs. It's best to create a minimized JRE using [jlink](https://docs.oracle.com/en/java/javase/11/tools/jlink.html) if you're using Java 9 or higher.
