### ISSUE TITLE
Game executable just stops after invoking main function

### ISSUE THREAD

**Issue by Frotty** [libgdx/packr#160]
Hi, I had Packr working for a couple of my builds, but now it simply does nothing.

Verbose console log:
![](https://i.imgur.com/15wV2Np.png)

Packr config (also tried without minimize and removelibs):
```java
val config = PackrConfig()
config.platform = PackrConfig.Platform.Windows64
config.jdk = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_windows_hotspot_8u242b08.zip"
config.executable = "oxrox"
config.classpath = listOf(gamePath)
config.resources = listOf(PACKED_ASSET_DIR.resolve("data").toFile())
config.removePlatformLibs = config.classpath
config.mainClass = "de.fatox.desktop.DesktopLauncher"
config.vmArgs = listOf("Xmx1G")
config.minimizeJre = "soft"
config.outDir = BUILD_DIR.toFile()

Packr().pack(config)
```

If I disable minimize and then run `.jre/bin/java.exe -jar game.jar` it works, so the packaged jre as well as my .jar are working totally fine, just the .exe for some reason stopped doing anything.

**Comment by tommyettinger** [comment]
I should mention that this particular JAR only runs if you use Java 8, HotSpot JIT. It has a weird crash immediately on Java 8, OpenJ9 JIT:

```
Exception in thread "main" java.lang.ClassFormatError: JVMCFRE068 class name is invalid; class=com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration, offset=0
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:397)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
        at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
        at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
        at java.security.AccessController.doPrivileged(AccessController.java:770)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:952)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:897)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:880)
        at de.fatox.desktop.DesktopLauncher.main(DesktopLauncher.kt:22)
```

As well as on Java 13, HotSpot:
```
Exception in thread "main" java.lang.ClassFormatError: Illegal class name "Lcom/badlogic/gdx/Files$FileType;" in class file com/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:823)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:721)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:644)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at de.fatox.desktop.DesktopLauncher.main(DesktopLauncher.kt:22)
```

I wonder if the DesktopLauncher.kt (Kotlin launcher as opposed to the normal Java) is relevant; that has caused bugs before. I have no idea what the source is like other than it uses LWJGL3, Kotlin and heavy reflection. Part of the bug may have been related to a dependency on gdx-tools, but I can't find that in the latest JAR and the problem was unchanged. There's a lot of... weird junk in the JAR. Here's the listing of `com/badlogic/gdx/` from inside the JAR, which should usually not be changed by user code or tooling:

```
Application$ApplicationType.class
Application.class
ApplicationAdapter.class
ApplicationListener.class
ApplicationLogger.class
assets
audio
Audio.class
backends
controllers
controllers.gwt.xml
files
Files$FileType.class
Files.class
Game.class
Gdx.class
graphics
Graphics$BufferFormat.class
Graphics$DisplayMode.class
Graphics$GraphicsType.class
Graphics$Monitor.class
Graphics.class
input
Input$Buttons.class
Input$Keys.class
Input$Orientation.class
Input$Peripheral.class
Input$TextInputListener.class
Input.class
InputAdapter.class
InputEventQueue.class
InputMultiplexer.class
InputMultiplexerprocessorsTypeToken.class
InputProcessor.class
LifecycleListener.class
maps
math
net
Net$HttpMethods.class
Net$HttpRequest.class
Net$HttpRequestheadersTypeToken.class
Net$HttpResponse.class
Net$HttpResponseListener.class
Net$Protocol.class
Net.class
OptimizedApplicationAdapterTypeAdapter.class
OptimizedFiles$FileTypeTypeAdapter.class
OptimizedGameTypeAdapter.class
OptimizedGraphics$BufferFormatTypeAdapter.class
OptimizedGraphics$DisplayModeTypeAdapter.class
OptimizedGraphics$MonitorTypeAdapter.class
OptimizedInputAdapterTypeAdapter.class
OptimizedInputEventQueueTypeAdapter.class
OptimizedInputMultiplexerTypeAdapter.class
OptimizedNet$HttpRequestTypeAdapter.class
OptimizedNet$ProtocolTypeAdapter.class
OptimizedScreenAdapterTypeAdapter.class
Preferences.class
scenes
Screen.class
ScreenAdapter.class
utils
Version.class
```

The TypeToken files look strange, as do the OptimizedFooBar classes.

**Comment by Frotty** [comment]
Turns out Proguard's `library/gson` optimizations make the .jar unable to run via OpenJ9 and Packr's JNI voodoo. Disabling it solves the issue. Thanks @tommyettinger

**Comment by tommyettinger** [comment]
Hooray, mystery solved! Great work, gang.
