### ISSUE TITLE
File Access Denied Exception on Win10

### ISSUE THREAD

**Issue by recepsahin** [libgdx/packr#181]
I get following exception with packr 3.0.1 but when I run packr 2.7.0 with the same configuration file everything works fine:

`java -jar packr-all-3.0.1.jar packr_config.json
Copying executable ...
Copying classpath(s) ...
Unpacking JRE ...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
java.nio.file.AccessDeniedException: C:\Users\User\AppData\Local\Temp\packr_temp\tmp\jdk-11.0.9.1+1-jre\man\ja
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:98)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:283)
        at java.base/java.nio.file.Files.copy(Files.java:1294)
        at com.badlogicgames.packr.PackrFileUtils$1.visitFile(PackrFileUtils.java:71)
        at com.badlogicgames.packr.PackrFileUtils$1.visitFile(PackrFileUtils.java:59)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.badlogicgames.packr.PackrFileUtils.copyDirectory(PackrFileUtils.java:59)
        at com.badlogicgames.packr.Packr.copyAndMinimizeJRE(Packr.java:413)
        at com.badlogicgames.packr.Packr.pack(Packr.java:175)
        at com.badlogicgames.packr.Packr.main(Packr.java:75)`

When I first run packr 2.7.0 and keep the jre file in temp folder and then run packr 3.0.1: 

`java -jar packr-all-2.7.0.jar packr_config.json
Cleaning output directory 'linux-deploy' ...
Copying executable ...
Copying classpath(s) ...
Unpacking JRE ...
Minimizing JRE ...
Copying resources ...
Removing foreign platform libs ...
Didn't detect any compression for archive linux-deploy\My.jar: No Compressor found for the stream signature.
Done!`

`java -jar packr-all-3.0.1.jar packr_config.json
Copying executable ...
Copying classpath(s) ...
Using cached JRE in 'C:\Users\User\AppData\Local\Temp\packr_temp' ...
Copying resources ...
Removing foreign platform libs ...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Done!`

I think there is a problem with the extraction method of the packr 3.0.1.

**Comment by karlsabo** [comment]
What's your packr_config look like?

**Comment by recepsahin** [comment]
> What's your packr_config look like?

Content of my config file is below:
`{
    "cachejre": "C:\\Users\\User\\AppData\\Local\\Temp\\packr_temp",
    "classpath": [
        "My.jar",
        "lib\\myLib.jar"
    ],
    "executable": "MyApplication",
    "jdk": "OpenJDK11U-jre_x64_linux_hotspot_11.0.9.1_1.tar.gz",
    "mainclass": "com.ui.UIController",
    "output": "linux-deploy",
    "platform": "linux64",
    "libs": "libs",
    "resources": [
        "resources"
    ],
    "useZgcIfSupportedOs": false,
    "removelibs": [
        "My.jar"
    ],
    "verbose": "-v",
    "vmargs": [
        "Xmx1G"
    ],
    "minimizejre": "soft"
 }`

**Comment by karlsabo** [comment]
Don't use minimize JRE on With Java 11, it won't do anything good. I would also remove JRE caching at that point (which would resolve your issue, I think). If you want to minimize the JRE, use jlink, there are examples in the packr source.

Do you really need to remove native libraries from your JAR? If not this step just wastes time and can corrupt service loader meta-inf.

**Comment by recepsahin** [comment]
Hi Karl, I've simplified my config file like this:

`{ "classpath": [ "My.jar", "lib\\myLib.jar" ], "executable": "MyApplication", "jdk": "OpenJDK11U-jre_x64_linux_hotspot_11.0.9.1_1.tar.gz", "mainclass": "com.ui.UIController", "output": "release", "platform": "linux64", "useZgcIfSupportedOs": false, "removelibs": [ "My.jar" ], "verbose": "-v", "vmargs": [ "Xmx1G" ] }`

But the problem continues:

`java -jar packr-all-3.0.1.jar linux_config.json
Copying executable ...
Copying classpath(s) ...
Unpacking JRE ...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
java.nio.file.AccessDeniedException: C:\Users\User\Documents\workspace\Linux\release\tmp\jdk-11.0.9.1+1-jre\man\ja
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:98)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:283)
        at java.base/java.nio.file.Files.copy(Files.java:1294)
        at com.badlogicgames.packr.PackrFileUtils$1.visitFile(PackrFileUtils.java:71)
        at com.badlogicgames.packr.PackrFileUtils$1.visitFile(PackrFileUtils.java:59)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.badlogicgames.packr.PackrFileUtils.copyDirectory(PackrFileUtils.java:59)
        at com.badlogicgames.packr.Packr.copyAndMinimizeJRE(Packr.java:413)
        at com.badlogicgames.packr.Packr.pack(Packr.java:175)
        at com.badlogicgames.packr.Packr.main(Packr.java:75)`

The error occurs  always while accessing "\jdk-11.0.9.1+1-jre\man\ja" file;  "ja" is a symbolic link file. When I check "man" folder, I see that "ja" is a shortcut; but when I use 2.7.0 version I see that "ja" is a normal file, not a shortcut. I think the root cause is extracting and accessing symbolic link files.

**Comment by karlsabo** [comment]
Please try the latest 3.0.3-SNAPSHOT <https://artifactory.nimblygames.com/artifactory/ng-public-snapshot/com/badlogicgames/packr/packr-all/3.0.3-SNAPSHOT/>.

I updated the directory copy to recreate relative symbolic links. Testing on Linux works, hopefully it works on Windows 10 too.

**Comment by recepsahin** [comment]
Thank you so much, it works very well. I've generated Linux distribution on Win 10 and tested on Ubuntu, everything is OK.  I'll close the issue if it is Ok for you too.

**Comment by karlsabo** [comment]
No worries, the issue will close when I merge the PR.
