### ISSUE TITLE
AccessDeniedException

### ISSUE THREAD

**Issue by Faust90** [libgdx/packr#213]
Hi all,

I'm having and issue while using packr. The generated executable works fine, but still it doesn't seems to complete the process without errors. Here the log.

```
E:\Game Development>java -jar packr-all-4.0.0.jar "E:\Repositories\LHIP\LHIT_packr_conf.json"
Copying executable ...
Copying classpath(s) ...
Unpacking JRE ...
java.nio.file.AccessDeniedException: LHIT_win\tmp\jre\bin\server\classes.jsa
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at com.badlogicgames.packr.PackrFileUtils$2.visitFile(PackrFileUtils.java:96)
        at com.badlogicgames.packr.PackrFileUtils$2.visitFile(PackrFileUtils.java:94)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at com.badlogicgames.packr.PackrFileUtils.deleteDirectory(PackrFileUtils.java:94)
        at com.badlogicgames.packr.Packr.copyAndMinimizeJRE(Packr.java:416)
        at com.badlogicgames.packr.Packr.pack(Packr.java:175)
        at com.badlogicgames.packr.Packr.main(Packr.java:75)
```
 The "classes.jsa" file is present in "E:\Game Development\LHIT_win\tmp\jre\bin\server" folder. 

Here the json conf.

```
{
    "platform": "windows64",
    "jdk": "C:\\Program Files\\Java\\jdk1.8.0_111",
    "executable": "LHIT",
    "classpath": [
        "E:\\Repositories\\LHIP\\desktop\\build\\libs\\desktop-1.0.jar"
    ],
    "mainclass": "faust.lhitgame.desktop.DesktopLauncher",
    "minimizejre": "soft",
    "output": "LHIT_win"
}
```

Thank you in advance.

**Comment by Faust90** [comment]
It was in read only and I didn't know it. Removing the attribute solved the problem, thank you

**Comment by jesusbmx** [comment]
Navigate to the folder "C:\Program Files (x86)\Java\jdk1.8.0_202\jre\bin\client". Right-click on the `classes.jsa` file and select "Properties". In the "General" tab, uncheck the "Read-only" option and click the "OK" button.
