### ISSUE TITLE
IOException with macosx and jar minification

### ISSUE THREAD

**Issue by moribellamy** [libgdx/packr#47]
get this trace:

```
Unpacking JRE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
copying resources
minimizing JRE
unpacking rt.jar
packing rt.jar
Exception in thread "main" org.zeroturnaround.zip.ZipException: java.io.IOException: File out-linux64/myjar.jar.tmp/META-INF/license exists and is not a directory. Unable to create directory.
        at org.zeroturnaround.zip.ZipUtil.rethrow(ZipUtil.java:2556)
        at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:379)
        at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:704)
        at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:689)
        at com.badlogicgames.packr.Packr.minimizeJre(Packr.java:216)
        at com.badlogicgames.packr.Packr.pack(Packr.java:157)
        at com.badlogicgames.packr.Packr.main(Packr.java:345)
Caused by: java.io.IOException: File out-linux64/myjar.jar.tmp/META-INF/license exists and is not a directory. Unable to create directory.
        at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:1482)
        at org.zeroturnaround.zip.ZipUtil$Unpacker.process(ZipUtil.java:822)
        at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:368)
```

```
{
    "platform": "linux64",
    "jdk": "/Users/mori/jres/openjdk-1.7.0-u80-unofficial-linux-amd64-installer.zip",
    "executable": "myjar",
    "appjar": "myjar.jar",
    "mainclass": "com.moribellamy.Main",
    "vmargs": [
       "-Xmx1G"
    ],
    "resources": [
    ],
    "minimizejre": "soft",
    "outdir": "out-linux64"
}
```

Oddly, i dont have this problem when i don't use jar minification on mac. When I run on ubuntu, I can use minification and the whole thing works.

**Comment by karlsabo** [comment]
The latest version of packr has changed how JARs are recreated, please try the latest version and open a new issue if you run into problems.
