### ISSUE TITLE
target to mac failed to load/find main class

### ISSUE THREAD

**Issue by piotrekuczy** [libgdx/packr#51]
## I have simple config file:

{
    "platform": "mac",
    "jdk": "/Users/piotrek/Documents/dev/packr/openjdk-1.7.0-u80-unofficial-macosx-x86_64-image.zip",
    "executable": "myapp",
    "classpath": [
        "desktop-1.0.jar"
    ],
    "mainclass": "pl/edu/piotrekuczy/desktop/DesktopLauncher",
    "vmargs": [
       "-Xmx1G"
    ],
    "minimizejre": "soft",
    "outdir": "out-mac"
}

## and after all myapp can't find a mainclass:

Exception in thread "main" java.lang.NoClassDefFoundError: IllegalName: pl/edu/piotrekuczy/desktop/DesktopLauncher
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:655)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:794)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Error: failed to load/find main class pl/edu/piotrekuczy/desktop/DesktopLauncher
logout

## what is wrong?

**Comment by code-disaster** [comment]
Did you upgrade from a previous packr version? The "mainclass" packages need to be separated by dots now, so:

```"mainclass": "pl.edu.piotrekuczy.desktop.DesktopLauncher"```

**Comment by piotrekuczy** [comment]
it works, thank You

**Comment by oliver108** [comment]
I also have the problem with the main class not being found, although I am using dot notation. I am using packr 4.0.0.

```
{
    "platform": "mac",
    "jdk": "./OpenJDK21U-jre_x64_mac_hotspot_21.0.4_7.tar.gz",
    "executable": "transense",
    "classpath": [
        "TranSense.jar",
		"../../release/librun"
    ],
    "mainclass": " de.ohenning.transense.TranSense",
    "vmargs": [
       "-Xmx1G"
    ],
    "resources": [
    ],
    "minimizejre": "soft",
    "output": "TranSense.app"
}
```
$ java -jar packr-all-4.0.0.jar transense_build_config_mac.json
Copying executable ...
Copying classpath(s) ...
Unpacking JRE ...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Minimizing JRE ...
Copying resources ...
Done!

/Applications/TranSense.app/Contents/MacOS/transense ; exit;
oliver@MBP-von-Oliver ~ % /Applications/TranSense.app/Contents/MacOS/transense ; exit;
Exception in thread "main" java.lang.ClassNotFoundException:  de.ohenning.transense.TranSense
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
Error: failed to load/find main class  de.ohenning.transense.TranSense

```
package de.ohenning.transense;
public class TranSense { ...
```

Content of Resources folder of target app:
TranSense.jar	jre		librun		transense.json
