### ISSUE TITLE
Exception running packr

### ISSUE THREAD

**Issue by stile1201** [libgdx/packr#89]
Hi,

I'm getting the following exception when trying to use the latest version of packr (downloaded in binary form from the readme in this repo).

Nicks-MacBook-Pro:packr-test nick$ java -jar packr.jar --platform mac --jdk /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home --executable msv --classpath viewserver-mosaic.jar --mainclass com.mosaicsmartdata.msv.viewserver.sellside.demo.Main --vmargs Xmx1G --resources config.xml license.lic log4j2.xml viewserver-sellside-demo.h2.db --minimizejre soft --output out --icon GenericApp.icns --bundle com.mosaicsmartdata.msv.viewserver
Cleaning output directory '/Users/nick/Temp/packr-test/out' ...
Copying executable ...
Copying classpath(s) ...
Unpacking JRE ...
Copying resources ...
Minimizing JRE ...
Removing foreign platform libs ...
Exception in thread "main" org.zeroturnaround.zip.ZipException: java.io.IOException: File out/Contents/Resources/viewserver-mosaic.jar.tmp/license exists and is not a directory. Unable to create directory.
	at org.zeroturnaround.zip.ZipUtil.rethrow(ZipUtil.java:2556)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:379)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:704)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:689)
	at com.badlogicgames.packr.PackrReduce.removePlatformLibs(PackrReduce.java:204)
	at com.badlogicgames.packr.Packr.pack(Packr.java:65)
	at com.badlogicgames.packr.Packr.main(Packr.java:308)
Caused by: java.io.IOException: File out/Contents/Resources/viewserver-mosaic.jar.tmp/license exists and is not a directory. Unable to create directory.
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:1482)
	at org.zeroturnaround.zip.ZipUtil$Unpacker.process(ZipUtil.java:822)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:368)
	... 5 more

I'd be very grateful if you could help me get past this.

Thanks,
Nick

**Comment by code-disaster** [comment]
Can you check if your .jar file contains both a "license" file and a "license" folder in the root directory? Just trying to understand what the ZipUtil class is complaining about.

**Comment by karlsabo** [comment]
Please try the latest version of packr and open a new issue if you run into any problems.
