### ISSUE TITLE
Soft profile not so conservative

### ISSUE THREAD

**Issue by mgsx-dev** [libgdx/packr#95]
For people facing same issue, Sun media package is required for libgdx games using microphone on linux.

```
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: com/sun/media/sound/JDK13Services
	at javax.sound.sampled.AudioSystem.getProviders(AudioSystem.java:1629)
	at javax.sound.sampled.AudioSystem.getMixerProviders(AudioSystem.java:1376)
	at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:409)
	at javax.sound.sampled.AudioSystem.getTargetDataLine(AudioSystem.java:700)
	at com.badlogic.gdx.backends.lwjgl.audio.JavaSoundAudioRecorder.<init>(JavaSoundAudioRecorder.java:36)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newAudioRecorder(OpenALAudio.java:343)

```

This package is excluded using soft profile. So workaround is to write your own profile (derived from soft profile) and remove this package exclusion.

I'm just wondering if Packr soft configuration is intended to work with libgdx core features.

**Comment by code-disaster** [comment]
The number of libGDX desktop projects which use packr + minimize + the microphone at the same time is probably pretty small, so nobody took notice until now.

Also, there is no ongoing "contract" between libGDX and packr, so things may break. If you use minimize, you should test all code paths for missing classes.

**Comment by mgsx-dev** [comment]
I fully understand but it would be nice to warn packr/libgdx users about this (and other) limitations in some way : packr wiki or readme ? libgdx wiki ?

@badlogic : what do you think ?

**Comment by karlsabo** [comment]
The [readme](https://github.com/libgdx/packr#jre) makes it pretty clear com/sun/media will get removed w/ the soft profile.
